_base_ = ["./base_e2e.py"]

# Preserve the UniAD-base architecture and replace only modules that need the
# repository's ONNX/TensorRT-compatible forward implementations.
model = dict(
    type="UniADTRT",
    img_backbone=dict(
        dcn=dict(type="DCNv2P", deform_groups=1, fallback_on_stride=False),
    ),
    pts_bbox_head=dict(
        type="BEVFormerTrackHeadTRTP",
        transformer=dict(
            type="PerceptionTransformerUniADTRTP",
            encoder=dict(
                type="BEVFormerEncoderTRTP",
                transformerlayers=dict(
                    type="BEVFormerLayerTRTP",
                    attn_cfgs=[
                        dict(
                            type="TemporalSelfAttentionTRTP",
                            embed_dims=256,
                            num_levels=1,
                        ),
                        dict(
                            type="SpatialCrossAttentionTRTP",
                            pc_range=[-51.2, -51.2, -5.0, 51.2, 51.2, 3.0],
                            deformable_attention=dict(
                                type="MSDeformableAttention3DTRTP",
                                embed_dims=256,
                                num_points=8,
                                num_levels=4,
                            ),
                            embed_dims=256,
                        ),
                    ],
                ),
            ),
            decoder=dict(
                type="DetectionTransformerDecoderTRTP",
                transformerlayers=dict(
                    attn_cfgs=[
                        dict(
                            type="MultiheadAttention",
                            embed_dims=256,
                            num_heads=8,
                            dropout=0.1,
                        ),
                        dict(
                            type="CustomMSDeformableAttentionTRTP",
                            embed_dims=256,
                            num_levels=1,
                        ),
                    ]
                ),
            ),
        ),
    ),
    seg_head=dict(
        type="PansegformerHeadTRTP",
        transformer=dict(
            encoder=dict(
                transformerlayers=dict(
                    attn_cfgs=dict(
                        type="MultiScaleDeformableAttentionTRTP",
                        embed_dims=256,
                        num_levels=4,
                    )
                )
            ),
            decoder=dict(
                transformerlayers=dict(
                    attn_cfgs=[
                        dict(
                            type="MultiheadAttention",
                            embed_dims=256,
                            num_heads=8,
                            dropout=0.1,
                        ),
                        dict(
                            type="MultiScaleDeformableAttentionTRTP",
                            embed_dims=256,
                            num_levels=4,
                        ),
                    ]
                )
            ),
        ),
    ),
    occ_head=dict(type="OccHeadTRTP"),
    motion_head=dict(
        type="MotionHeadTRTP",
        transformerlayers=dict(
            type="MotionTransformerDecoderTRTP",
            transformerlayers=dict(
                type="MotionTransformerAttentionLayerTRTP",
                attn_cfgs=[
                    dict(
                        type="MotionDeformableAttentionTRTP",
                        num_steps=12,
                        embed_dims=256,
                        num_levels=1,
                        num_heads=8,
                        num_points=4,
                        sample_index=-1,
                    )
                ],
            ),
        ),
    ),
    planning_head=dict(type="PlanningHeadSingleModeTRTP"),
)
